#這些是LINE官方開放的套件組合透過import來套用這個檔案上
from linebot import (LineBotApi, WebhookHandler)
from linebot.exceptions import (InvalidSignatureError)
from linebot.models import *

#旋轉木馬按鈕訊息介面
def Carousel_Template():
    message = TemplateSendMessage(
        alt_text='一則旋轉木馬按鈕訊息',
        template=CarouselTemplate(
            columns=[
                CarouselColumn(
                    thumbnail_image_url='https://yahui1201.files.wordpress.com/2010/12/e78cb4e7a19001.jpg',
                    title='猴硐煤礦博物園區',
                    text='每週一~週日08:00 - 18:00',
                    actions=[
                        PostbackTemplateAction(
                            label='224新北市瑞芳區柴寮路42號',
                            uri='https://goo.gl/maps/9hu4pJL4UYcVoarbA'
                        ),
                        URITemplateAction(
                            label='造訪網站↗',
                            uri='https://newtaipei.travel/zh-tw/attractions/detail/110748'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='https://choyce.tw/wp-content/uploads/20200903235438_27.jpg',
                    title='猴硐礦工文史館',
                    text='每週二~週日09:00`17:00(週一休館)',
                    actions=[
                        PostbackTemplateAction(
                            label='224新北市瑞芳區柴寮路25號',
                            uri='https://goo.gl/maps/CoUX1RF5E9WpTfgs5'
                        ),
                        URITemplateAction(
                            label='造訪網站↗',
                            uri='https://smiletaiwan.cw.com.tw/article/5458'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='https://cw1.tw/CP/images/article/P1400560129646.jpg',
                    title='金瓜石黃金博物園區',
                    text='平日09:30~17:00、假日及國定09:30~18:00',
                    actions=[
                        PostbackTemplateAction(
                            label='224新北市瑞芳區金光路8號',
                            uri='https://goo.gl/maps/75GXCARquVL6NyZZ8'
                        ),
                        URITemplateAction(
                            label='造訪網站↗',
                            uri='https://www.gep.ntpc.gov.tw/xmdoc/cont?xsmsid=0G246368552167800609'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='http://img3.okgo.tw/titlepic/b2925_1.jpg',
                    title='九份昇平戲院',
                    text='平日:09:30-17:30、假日:09:30-18:00',
                    actions=[
                        PostbackTemplateAction(
                            label='224新北市瑞芳區輕便路137號',
                            uri='https://goo.gl/maps/Nqyd78zJohFJLh2aA'
                        ),
                        URITemplateAction(
                            label='造訪網站↗',
                            uri='https://newtaipei.travel/zh-tw/attractions/detail/110024'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='https://www.welcometw.com/wp-content/uploads/2020/jiufen/04/%E4%B9%9D%E4%BB%BD%E9%87%91%E7%A4%A6%E5%8D%9A%E7%89%A9%E9%A4%A83-scaled.jpg',
                    title='九份金礦博物館',
                    text='平日:10:00-18:00 假日:09:00-18:00',
                    actions=[
                        PostbackTemplateAction(
                            label='224新北市瑞芳區石碑巷66號',
                            uri='https://goo.gl/maps/QRZV72fjBy2uPNWD9'
                        ),
                        URITemplateAction(
                            label='造訪網站↗',
                            uri='https://newtaipei.travel/zh-tw/attractions/detail/110668'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='https://www.welcometw.com/wp-content/uploads/2020/jiufen/03/RIMG4606-scaled.jpg',
                    title='九份木屐王',
                    text='營業時間:9:00~18:30',
                    actions=[
                        PostbackTemplateAction(
                            label='224新北市瑞芳區基山街22號',
                            uri='https://goo.gl/maps/VMtkZqnoAK94yUUz9'
                        ),
                        URITemplateAction(
                            label='造訪網站↗',
                            uri='https://www.tripadvisor.com.tw/Attraction_Review-g13806837-d6554500-Reviews-Jiufen_Wooden_Clog_Shop-Ruifang_New_Taipei.html'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='http://photox.pchome.com.tw/s99/dhlee22560373/477/139167559584/',
                    title='猴硐壺穴觀景台',
                    text='無',
                    actions=[
                        PostbackTemplateAction(
                            label='224新北市瑞芳區柴寮路',
                            uri='https://goo.gl/maps/DjoTDz4JR992unXr7'
                        ),
                        URITemplateAction(
                            label='造訪網站↗',
                            uri='https://www.tripadvisor.com.tw/Attraction_Review-g13806837-d6955811-Reviews-Husyue_Dising-Ruifang_New_Taipei.html'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='https://d1ralsognjng37.cloudfront.net/69d3f3d4-abd2-43ef-ba90-e9497bc47dd6.jpeg?width=500',
                    title='阿珠姐肉羹',
                    text='10:00-19:00 (周休五日,只有假日營業)',
                    actions=[
                        PostbackTemplateAction(
                            label='新北市瑞芳區魚寮路154號',
                            uri='https://goo.gl/maps/pL6JsY7e33DM6dU76'
                        ),
                        URITemplateAction(
                            label='造訪網站↗',
                            uri='https://www.walkerland.com.tw/article/view/288371'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='https://auntie.tw/wp-content/uploads/DSC06801_batch.jpg',
                    title='文瓊小築',
                    text='無',
                    actions=[
                        PostbackTemplateAction(
                            label='新北市瑞芳區魚寮路152號 ',
                            uri='https://goo.gl/maps/LEA8gsBatqTJDtZY7'
                        ),
                        URITemplateAction(
                            label='造訪網站↗',
                            uri='https://auntie.tw/wen-qiong/'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='https://d.share.photo.xuite.net/yuhyng/1d6308d/19828679/1123337414_m.jpg',
                    title='猴硐神社遺址',
                    text='全天開放',
                    actions=[
                        PostbackTemplateAction(
                            label='224新北市瑞芳區侯硐路61號',
                            uri='https://goo.gl/maps/6aX7TyBd9zEUPjE26'
                        ),
                        URITemplateAction(
                            label='造訪網站↗',
                            uri='http://tamsui.dils.tku.edu.tw/wiki/index.php/%E7%8C%B4%E7%A1%90%E7%A5%9E%E7%A4%BE%E9%81%BA%E5%9D%80'
                        )
                    ]
                ),
            ]
        )
    )


    return message